/* Agendamento (#/agendar): formulário e mensagem para WhatsApp. */
views.agendar=()=>`<section class="split"><div style="max-width:560px"><h2>Agendar tatuagem</h2><div class="note">Versão de demonstração: nenhum dado é salvo. Ao final, você recebe a mensagem pronta para enviar pelo WhatsApp.</div>
<form id="book"><label>Nome<input name="n" required autocomplete="name"></label><label>WhatsApp<input name="w" required inputmode="tel" autocomplete="tel" pattern="\\(?\\d{2}\\)?\\s?9?\\d{4}-?\\d{4}" title="Use DDD + número, ex.: (11) 90000-0000" placeholder="(11) 90000-0000"></label>
<label>Estilo<select name="s">${styles.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></label>
<label>Parte do corpo (opcional)<select name="b"><option value="">Ainda não sei</option>${Object.entries(body).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>
<label>Tamanho (opcional)<select name="z"><option value="">Ainda não sei</option>${Object.entries(sizes).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>
<label>Data preferida<input type="date" name="d" required min="${new Date().toLocaleDateString('sv')}"></label><label>Conte sua ideia<textarea name="m" rows="4" placeholder="Referências, detalhes, cores…"></textarea></label>
<button class="btn solid" type="submit">Enviar pedido</button></form></div><aside>h3 style="font-size:22px;margin-bottom:12px">Como funciona</h3><ol class="steps"><li>Preencha o pedido com sua ideia e uma data.</li><li>Envie a mensagem pronta pelo WhatsApp.</li><li>O estúdio responde para confirmar a data.</li></ol></aside></section>`;
document.addEventListener('submit',e=>{if(e.target.id!=='book')return;e.preventDefault();const d=Object.fromEntries(new FormData(e.target));
const msg=[`Olá! Quero agendar uma tatuagem no ${studio.name}.`,`Nome: ${d.n}`,`Estilo: ${S[d.s].name}`,d.b&&`Parte do corpo: ${body[d.b]}`,d.z&&`Tamanho: ${sizes[d.z]}`,`Data preferida: ${d.d.split('-').reverse().join('/')}`,d.m&&`Ideia: ${d.m}`].filter(Boolean).join('\n');
views._msg=msg;
$('app').innerHTML=`<section style="max-width:560px"><h2>Pedido pronto para enviar</h2><p>Obrigado, ${esc(d.n)}. Envie esta mensagem pelo WhatsApp para confirmar a data com o estúdio.</p><pre class="msg">${esc(msg)}</pre><p><a class="btn solid" href="https://wa.me/${studio.wa}?text=${encodeURIComponent(msg)}" target="_blank" rel="noopener">Abrir no WhatsApp</a> <button class="btn" id="cp" type="button">Copiar mensagem</button> <a class="btn" href="#/">Voltar ao início</a></p></section>`;scrollTo(0,0)});
